import json
from pathlib import Path

import pandas as pd

from timetable_exporter.week_view_exporter import build_week_view_workbook


def test_week_view_template_footer_has_repo_link():
    template_path = Path(__file__).resolve().parents[1] / "data" / "presets" / "week_view.template.json"
    cfg = json.loads(template_path.read_text(encoding="utf-8"))

    lines = (cfg.get("footer") or {}).get("lines") or []
    assert lines, "Expected default template to include footer.lines"

    first = lines[0]
    assert first.get("text") == "Generated by timetable-exporter github.com/zmdev2082/timetable-exporter"
    assert "url" not in first



def test_week_view_footer_plain_text_not_hyperlinked():
    # Minimal single booking
    df = pd.DataFrame(
        [
            {
                "Day": "Monday",
                "Start": "09:00",
                "End": "10:00",
                "Summary": "TEST1000",
                "Week": "S1C WK 1",
            }
        ]
    )

    cfg = {
        "include_week_pattern": False,
        "columns": {
            "day": "Day",
            "start_time": "Start",
            "end_time": "End",
            "duration": None,
            "summary": "Summary",
            "week_pattern": "Week",
        },
        "layout": {
            "days": ["Monday"],
            "start_time": "08:00",
            "end_time": "11:00",
            "interval_minutes": 60,
        },
        "formatting": {
            "row_height": 20,
            "day_column_width": 15,
            "time_column_width": 10,
        },
        "footer": {
            "lines": [
                {
                    "text": "Generated by timetable-exporter github.com/zmdev2082/timetable-exporter",
                },
            ]
        },
    }

    wb = build_week_view_workbook(df, cfg)
    ws = wb.active

    gen_cell = None
    for row in ws.iter_rows():
        for cell in row:
            if cell.value == "Generated by timetable-exporter github.com/zmdev2082/timetable-exporter":
                gen_cell = cell

    assert gen_cell is not None
    assert gen_cell.hyperlink is None
